server:
  port: 8082

spring:
  application:
    name: likelion-backend
  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=Asia/Seoul
    username: likelion
    password: likelion
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{36}] - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-5level) %yellow([%thread]) %green(%logger{36}) - %msg%n"
  config: classpath:logback/logback-spring2.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 필요한 항목만 노출해도 됨
  endpoint:
    health:
      show-details: always
