version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      #      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx_logs:/var/log/nginx
    ports:
      - "80:80"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command: ["-nginx.scrape-uri=http://nginx:80/nginx_status"]
    ports:
      - "9113:9113"
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./grafana/datasources/datasources.yml:/etc/prometheus/datasources.yml
      - ./data/prometheus-data:/prometheus
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nginx-exporter

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./conf/promtail-config.yml:/etc/promtail/config.yml
      - ./data/nginx_logs:/var/log/nginx
      - /var/log/nginx:/var/log/nginx
      - ../../logs:/var/log/spring-app # todo spring logs
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data:/var/lib/grafana
    ports:
      - "3200:3000"
    depends_on:
      - prometheus
      - loki
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"